# Generated by Django 5.2.7 on 2025-10-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_board_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='pin',
            field=models.IntegerField(blank=True),
        ),
    ]
