# Generated by Django 5.2.7 on 2025-10-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='pin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
