# Generated by Django 5.2.7 on 2025-10-05 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_board_code_alter_board_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pin',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
